/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


 */


  #include <iostream>
 #include <ctime>

 int run(int max, int* arr, int len){
     int sum = 0;
     for(int i = 0; i < max; i++){
         for(int j = 0; j < len; j++){
             if(i%arr[j]==0){
                sum += i;
                break;
             }
         }
     }
     return sum;
 }

 int main(){
     std::clock_t begin = std::clock();
     int len = 2;
     int dividers[len] = {3, 5};
     int max = 1000;
     int result = run(max, dividers, len);
     std::cout << "Result: " << result <<  std::endl;
     std::clock_t end = std::clock();
     std::cout << "Time taken: " << (end - begin) / CLOCKS_PER_SEC <<  std::endl;
     return 0;
 }